language: node_js

node_js:
  - "node" # Latest
  - "6"
  - "5"
  - "4"

services:
  - mongodb

before_install:
  - npm install -g newman 
  - npm install 

install:  
  - npm start &

before_script:
  - sleep 15 # for MongoDB & app start 

script: 
  - newman -c test/proxy-web.postman_collection.json -n 10 -e test/proxy-web-default.postman_environment.json
