sudo: required
language: node_js

node_js:
  - "node" # Latest
  - "6"

services:
  - mongodb
  - docker

branches:
  only:
  - master
  - dev
  - v3

before_install:
  - npm install -g newman 
  - npm install 

install:  
  - npm start &

before_script:
  - sleep 15 # for MongoDB & app start 

script: 
  - newman -s -c test/proxy-web.postman_collection.json -n 10 -e test/proxy-web-default.postman_environment.json

after_success:
  - docker build -t miton18/web-proxy .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
