language: node_js

node_js:
  - "node" # Latest
  - "6"
  - "5"
  - "4"

services:
  - mongodb

before_script:
  - sleep 15 # for MongoDB start
  - npm install -g gulp newman
  - npm install 

script: 
  - gulp test 
  - newman -s -c test/proxy-web.postman_collection.json -n 10 -e test/proxy-web-default.postman_environment.json
