sudo: required
language: node_js
node_js:
- node
- '6'
services:
- mongodb
- docker
branches:
  only:
  - master
  - dev
  - v3
cache:
   directories:
     - node_modules

before_install:
  - npm install -g newman
  - npm install
install:
  #- sudo $(which npm) start &
  - sudo docker build -t test .
before_script:
  #- sleep 45
  - sudo docker run -d --net=host -e PROXY_DB=$PROXY_DB -e PROXY_KEY=$PROXY_KEY -e PROXY_SALT=$PROXY_SALT -e PROXY_ENV=$PROXY_ENV test 
script:
  - sleep 15
  - npm test
  
after_success:
  - export PROJECT_VERSION=$(npm version patch)
  - sudo docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - sudo docker tag test miton18/web-proxy:$PROJECT_VERSION
  - sudo docker push miton18/web-proxy:$PROJECT_VERSION
  - sudo docker tag test miton18/web-proxy:latest
  - sudo docker push miton18/web-proxy:latest


notifications:
  hipchat:
    notify: true
    on_pull_requests: true
    template:
      #- '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    rooms:
      secure: wLG9HdqI6kz1HKKsrc1uVdOqPhIo/CylpFtJZ0j+qdoTOqJqNT2AhEqsjyXiCerv59UtEaqtGH6B5XPo1Ww5mcie5vBOss4ikQp3k9a3Xtl8E+PIW0V/ePDpKuRROcr0g/l/XldQLpB8PXHsu0MT0G9qYRwBWSq9mYhPVZzs2BiOFvIHjcS14kQrM3geHg5bWfsOAyuTlGeJOnt2gwTyIdG5BNhfr7OwmQzCV+gYowCNIcDEVGvb4INMVOE0LQ9Bq6BWFVIIz0EmutMcDpxzHSg2YYaCmo/IZRZZLAQMdIrZ0iEsx98jfmjjkS1PIMYrut8X/RmsALImkxVNn+Tnd7hAuLC1OHj6TKNtgh0o0A6TXTwIFp3bEu+n6fvkKtx5LAc8nO5yLf7KAWvuE3LFVzDsKGDdzkDDkDj0999PWSfcFKPtwsLU2Y2Whfp8D0Yr0O5Fans/GCAaLcRQCk5EVgsQYoK2SAXVHLOlnxfBePTBKG/miHmoddYypuWNv+d6UH9+mkph9IyIDE/XojasKUZ2NHgJ2twTJjESxuNWGwaC0296uCweJpzCHlm85UGaIJCWETLbvJenrKnZe4qQ3n3j4CA8oCcVKdQUF9wzmZ5T+mLiVl/dgaAzgffaXsDmAelUx4W10BZDwOf0+8GfCyWfpnFZgXzLwsmmQ/RHDdc=
